# Generated by Django 3.1.7 on 2021-05-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='user_id',
        ),
    ]
